// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNuHJaSTvplL9VO5qu5crZAFXMDiEXa5Y',
    appId: '1:1096280490889:web:2561dfccf0cc6f227a5758',
    messagingSenderId: '1096280490889',
    projectId: 'ely74-8b1b0',
    authDomain: 'ely74-8b1b0.firebaseapp.com',
    storageBucket: 'ely74-8b1b0.firebasestorage.app',
    measurementId: 'G-PPFWKBYTX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgtButpMVIkwVby0qQOOcSpkZgNrsJUQ',
    appId: '1:1096280490889:android:d731029794363b437a5758',
    messagingSenderId: '1096280490889',
    projectId: 'ely74-8b1b0',
    storageBucket: 'ely74-8b1b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKHjBd7x9hhPTGQQta5KJKhdA19qL38SA',
    appId: '1:1096280490889:ios:2d2ad88aae471fec7a5758',
    messagingSenderId: '1096280490889',
    projectId: 'ely74-8b1b0',
    storageBucket: 'ely74-8b1b0.firebasestorage.app',
    iosBundleId: 'com.bazarya.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKHjBd7x9hhPTGQQta5KJKhdA19qL38SA',
    appId: '1:1096280490889:ios:57d8d8ff5db5b75c7a5758',
    messagingSenderId: '1096280490889',
    projectId: 'ely74-8b1b0',
    storageBucket: 'ely74-8b1b0.firebasestorage.app',
    iosBundleId: 'com.example.marketPlace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNuHJaSTvplL9VO5qu5crZAFXMDiEXa5Y',
    appId: '1:1096280490889:web:a24fe608ba35f24c7a5758',
    messagingSenderId: '1096280490889',
    projectId: 'ely74-8b1b0',
    authDomain: 'ely74-8b1b0.firebaseapp.com',
    storageBucket: 'ely74-8b1b0.firebasestorage.app',
    measurementId: 'G-Q8TLJ3B8GR',
  );

}